apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: gitlab-cluster-image-policy
  namespace: default
spec:
  repositories:
    - name: docker.io/*
    - name: quay.io/kubernetes-ingress-controller/*
    - name: k8s.gcr.io/*
    - name: registry.gitlab.com/gitlab-org/build/cng/* 
    - name: docker.elastic.co/*
